# Generated by Django 5.0 on 2024-03-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
    ]
