# Generated by Django 5.0 on 2024-03-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='rank',
        ),
        migrations.AddField(
            model_name='song',
            name='tier',
            field=models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='S', max_length=1),
            preserve_default=False,
        ),
    ]
