# Generated by Django 5.0 on 2024-03-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_album_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='hours',
            field=models.CharField(default='1', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='minutes',
            field=models.CharField(default='1', max_length=3),
            preserve_default=False,
        ),
    ]
