# Generated by Django 5.0 on 2024-03-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_album_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField()),
            ],
        ),
    ]
