# Generated by Django 5.0.1 on 2024-08-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_profile_blogprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogProfile',
        ),
    ]
