# Generated by Django 5.0.8 on 2024-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
