# Generated by Django 5.0 on 2023-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coin_count', models.IntegerField()),
                ('coin_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
