# Generated by Django 5.0 on 2023-12-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodreviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reviewlink', models.CharField(max_length=100)),
                ('reviewPhotoLink', models.CharField(max_length=100)),
                ('reviewId', models.CharField(max_length=100)),
            ],
        ),
    ]
