# Generated by Django 5.0 on 2023-12-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_foodreviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foodreviews',
            new_name='foodreview',
        ),
    ]
