# Generated by Django 5.0 on 2023-12-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_foodreviews_foodreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreview',
            name='reviewId',
            field=models.DateTimeField(),
        ),
    ]
