# Generated by Django 5.0 on 2023-12-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_foodreview_reviewid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodreview',
            old_name='reviewId',
            new_name='reviewDate',
        ),
    ]
