# Generated by Django 5.0 on 2023-12-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_reviewid_foodreview_reviewdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreview',
            name='reviewBody',
            field=models.TextField(default='Empty'),
        ),
    ]
