# Generated by Django 5.0 on 2023-12-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_reviewbody_foodreview_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodreview',
            old_name='Body',
            new_name='linkhtml',
        ),
    ]
