# Generated by Django 5.0 on 2023-12-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_foodreview_linkhtml_foodreview_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreview',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='food_reviews/html/'),
        ),
    ]
