# Generated by Django 5.0 on 2023-12-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_foodreview_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodreview',
            name='html',
        ),
        migrations.RemoveField(
            model_name='foodreview',
            name='html_file',
        ),
    ]
