# Generated by Django 5.0 on 2023-12-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
