# Generated by Django 5.0 on 2023-12-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_account_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coin_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
