# Generated by Django 5.0 on 2024-07-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_redeemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemcode',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
