# Generated by Django 5.0.1 on 2024-08-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_profile_bio_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_url',
            new_name='discord_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pinterest_url',
            new_name='steam_url',
        ),
    ]
