# Generated by Django 5.0.1 on 2024-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coin_count',
            field=models.FloatField(default=0.0),
        ),
    ]
