# Generated by Django 5.0.1 on 2024-09-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_profile_coin_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coin_count',
            field=models.IntegerField(default=0),
        ),
    ]
