# Generated by Django 5.0.1 on 2024-09-08 21:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_profile_coin_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coin_count',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
