# Generated by Django 5.0.8 on 2024-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_profile_coin_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodreview',
            old_name='Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='foodreview',
            name='PhotoLink',
        ),
        migrations.AddField(
            model_name='foodreview',
            name='bob_marley',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='food_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='is_dynamic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='photo_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='stop_train',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodreview',
            name='would_sip',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodreview',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
