# Generated by Django 5.0.1 on 2025-01-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_nestedtodo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NestedTodo',
        ),
    ]
