# Generated by Django 5.0.1 on 2024-09-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stock_color_alter_stock_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
