# Generated by Django 5.0 on 2024-06-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worm',
            name='last_fed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worm',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worm',
            name='last_slept',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
