# Generated by Django 5.0 on 2024-06-21 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worm', '0004_worm_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
