# Generated by Django 5.0 on 2024-07-29 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worm', '0005_alter_worm_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='worm',
            name='times_revived',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
