# Generated by Django 5.0.1 on 2025-01-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_options_todoitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='collapsed',
            field=models.BooleanField(default=False),
        ),
    ]
